### ISSUE TITLE
How to use grafana resource's value

### ISSUE THREAD

**Issue by east4ming** [alxrem/terraform-provider-jsonnet#10]
For me, I create a "HOME" grafana dashboard. 
It contains some "dashboard list" panel, which "folderId" value should come the terraform resource `grafana_folder.example.id`, instead of hard code.
What am I supposed to do?

Thanks

**Comment by alxrem** [comment]
Hello.

```terraform
resource "grafana_folder" "example" {
  title = "Example"
}

data "jsonnet_file" "dashboard_list" {
  source = file("${path.module}/dashboards/list.jsonnet")

  ext_str = {
    folder_id = grafana_folder.example.id
  }
}
```

Folder ID will be accessible in jsonnet code as `std.extVar('folder_id')`

**Comment by east4ming** [comment]
Got it. Thanks
