### ISSUE TITLE
jsonnet_path not configured with content argument is used

### ISSUE THREAD

**Issue by groner** [alxrem/terraform-provider-jsonnet#12]
I'm trying to write a module that generates configuration from boilerplate that loads libraries along with a passed in snippet of jsonnet.

Unfortunately it seems that jsonnet_path is only set when jsonnet is specified by the source argument.
https://github.com/alxrem/terraform-provider-jsonnet/blob/927e71c67e153fec87deec0e90404812b504eea3/private/provider/data_source_jsonnet_file.go#L149-L163

<details>
<summary>Example usage</summary>

```terraform
variable "code" {
  type = string
}

variable "args" {
  type = any
  default = {}
}

data "jsonnet_file" "scrape_config" {
  jsonnet_path = "${path.module}/jsonnet"

  content =<<-EOF
    local prometheus = import "prometheus.libsonnet";
    local job = prometheus.job;

    function(${join(", ", keys(var.args))})
      ${var.code}
    EOF

  tla_code = { for k,v in var.args : k => jsonencode(v) }
}

output "rendered" {
  value = data.jsonnet_file.scrape_config.rendered
}
```

</details>

**Comment by alxrem** [comment]
Hello. It should be fixed in 2.3.2 release.

**Comment by groner** [comment]
I've updated 2.3.2 and it seems to be working for my use case.

Thanks for the speedy fix, @alxrem!

**Comment by groner** [comment]
Commenting again so I can close this.
