### ISSUE TITLE
Specify grafonnet library at the module-level

### ISSUE THREAD

**Issue by jacksongoode** [alxrem/terraform-provider-jsonnet#7]
We are having some issues where we would like to import grafonnet with a relative path like `local grafana = import '/grafonnet/grafana.libsonnet';` but the module's relative directory is something like `.terraform/modules/module-name/`.

So we've only gotten this working with `local grafana = import '.terraform/modules/module-name/grafonnet/grafana.libsonnet'` after packing the grafonnet library with the module.

It doesn't seem possible to configure the provider at a higher level since it wouldn't know the relative path of the module where graffonet is located. This is an issue specifically for us because we are trying to use the provider in a submodule.

Do you have any suggestions as to how you've gotten this working with adding the grafonnet library?

---

One thought: Would it be possible to add the grafonnet library at the module level so it would be possible to do something like this.
```tf
data "jsonnet_file" "dashboard_json" {
  jsonnet_path = "${path.module}/grafonnet"
  for_each     = fileset(path.module, "./dashboards/*.jsonnet")
  source       = "${path.module}/${each.key}"
}
```

@adkinsjd

**Comment by alxrem** [comment]
Hello.
`jsonnet_path` added to data source in v2.3.0 release.
